config/routes.rb
Rails.application.routes.draw do

  # Root page
  root to: "home#show"
  resource :home, only: [:show]

  # User sign up, sign in, and log in/log out
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  # routes for chat_rooms
  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'

  # routes for consultants
  resources :consultants

  # routes for consultant sessions
  resources :consultant_sessions do
    member do
      get '/video' => 'consultant_sessions#video', as: 'video'
    end
  end

  #routes for categories
  resources :categories, only: [:show, :index]
  get "/loans" => "categories#loans", as: "loans"

  resources :payments, only: [:new, :create]

  post '/consultants/:consultant_id/book_session', to: "consultant_sessions#book", as: "session_booking"

  get "/tax" => "categories#tax", as: "tax"
  get "/investments" => "categories#investments", as: "investments"
  get "/personal_finance" => "categories#personal_finance", as: "personal_finance"
  get "/insurance" => "categories#insurance", as: "insurance"
  get "/trading" => "categories#trading", as: "trading"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories.rb
class Category < ApplicationRecord
	has_many :consultants

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :category_consultants
	has_many :consultants, through: :category_consultants, foreign_key: 'consultant_id'

end

app/models/category_consultant.rb
class CategoryConsultant < ApplicationRecord
  belongs_to :category
  belongs_to :consultant
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  belongs_to :consultant_session
end

app/models/consultant.rb
class Consultant < ApplicationRecord
	belongs_to :user
	has_many :category_consultants
	has_many :categories, through: :category_consultants, foreign_key: 'category_id'
	has_many :users
	has_many :consultant_sessions

	validates :qualifications, :languages, :location, presence: true

end

app/models/consultant_session.rb
class ConsultantSession < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :consultant, class_name: 'User'
  has_many :chat_rooms
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/payment.rb
class Payment < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :consultants
  has_many :consultant_sessions, foreign_key: "consultant_id"
  has_many :consulting_sessions, class_name: "ConsultantSession", foreign_key: "user_id"
  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth[:info][:email]
      user.password = ('0'..'z').to_a.shuffle.first(8).join
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @categories = Category.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @client_token = Braintree::ClientToken.generate
    @total_cost = 0
    @consult_sessions = params[:consult_sessions].keys
    params[:consult_sessions].keys.each do |id|
      @consultant_session = ConsultantSession.find(id)
      @total_cost += @consultant_session.rate
    end
  end

  def create
    consult_sessions = params[:payment][:consult_sessions].split(" ")
    nonce = params[:payment_method_nonce]
    render action: :new and return unless nonce
    result = Braintree::Transaction.sale(
      amount: params[:payment][:total_cost],
      payment_method_nonce: params[:payment_method_nonce]
    )
    if result.success?
      consult_sessions.each do |id|
        @consultant_session = ConsultantSession.find(id)
        @consultant_session.update(user_id: current_user.id, session_active_inactive: false)
      end 
      flash[:success] = 'Payment has been made successfully'
      redirect_to root_path
    else
      flash[:error] = 'There was a problem with payment. Please try again.'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

before_action :set_user, only: [:show]

	def create
	    @user = user_from_params
	    if @user.save
	      ConfirmationMailer.confirmation_email(@user).deliver
	      sign_in @user
	      redirect_back_or url_after_create
	    else
	      flash[:message] = 'Invalid email/password combination'
	      render template: "users/new"
	    end
	  end

  def show

  end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
        if @user.update(filtered_user_params)
          redirect_to root_path
        else
          flash[:alert] = 'Error'
          render :edit
        end
    end

	private

	def user_from_params
	    email = user_params.delete(:email)
	    password = user_params.delete(:password)
	    birthday = user_params.delete(:birthday)
	    profile_picture = user_params.delete(:avatar)

	    Clearance.configuration.user_model.new(user_params).tap do |user|
	      user.email = email
	      user.password = password
	      user.birthday = birthday
	      user.avatar = profile_picture
	    end
	end

	def edit_user_params
		params.require(:user).permit(:email, :password, :birthday, :avatar)
	end

	def filtered_user_params
		if edit_user_params[:password].empty?
			edit_user_params.except(:password)
		else
			edit_user_params
		end
	end

   def set_user
     @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find(session[:user_id])
  end
end

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-default topNav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, html_options = {class: "navbar-brand"} do %>
        <%= image_tag('logo', size: "150x30") %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <% if current_user.consultants.empty? %>
          <li><%= link_to 'Become a consultant', new_consultant_path(current_user) %></li>
        <% else %>
          <li><%= link_to 'Dashboard', consultant_path(current_user.consultants.last) %></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Show your profile', user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
          </ul>
        </li>

      <% else %>
        <li class="signinButton"><span>Sign In</span></li>
      <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>