config/routes.rb
Rails.application.routes.draw do

  # Root page
  root to: "home#show"
  resource :home, only: [:show]

  # User sign up, sign in, and log in/log out
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  # routes for chat_rooms
  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'

  # routes for consultants
  resources :consultants

  # routes for consultant sessions
  resources :consultant_sessions do
    member do
      get '/video' => 'consultant_sessions#video', as: 'video'
    end
  end

  #routes for categories
  resources :categories, only: [:show, :index]
  get "/loans" => "categories#loans", as: "loans"

  resources :payments, only: [:new, :create]

  post '/consultants/:consultant_id/book_session', to: "consultant_sessions#book", as: "session_booking"

  get "/tax" => "categories#tax", as: "tax"
  get "/investments" => "categories#investments", as: "investments"
  get "/personal_finance" => "categories#personal_finance", as: "personal_finance"
  get "/insurance" => "categories#insurance", as: "insurance"
  get "/trading" => "categories#trading", as: "trading"

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  belongs_to :consultant_session
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<div class="container-fluid bodyWrapper">
  <br />
  <h1>Chat rooms</h1>

  <p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

  <ul>
    <%= render @chat_rooms %>
  </ul>
</div>

app/views/chat_rooms/new.html.erb
<div class="container-fluid bodyWrapper">
  <br />
  <h1>Add chat room</h1>

  <%= form_for @chat_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Add!", class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/chat_rooms/show.html.erb
<div class="container-fluid bodyWrapper">
  <br />
  <h1><%= @chat_room.title %></h1>

  <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
  </div>

  <%= form_for @message, url: '#', :html => {:id => "new_message"} do |f| %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %>
      <small class="text-muted">From 2 to 1000 characters</small>
    </div>

    <%= f.submit "Post", class: 'btn btn-primary btn-lg', id: 'new_message' %>
  <% end %>
</div>