config/routes.rb
Rails.application.routes.draw do

  # Root page
  root to: "home#show"
  resource :home, only: [:show]

  # User sign up, sign in, and log in/log out
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  # routes for chat_rooms
  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'

  # routes for consultants
  resources :consultants

  # routes for consultant sessions
  resources :consultant_sessions do
    member do
      get '/video' => 'consultant_sessions#video', as: 'video'
    end
  end

  #routes for categories
  resources :categories, only: [:show, :index]
  get "/loans" => "categories#loans", as: "loans"

  resources :payments, only: [:new, :create]

  post '/consultants/:consultant_id/book_session', to: "consultant_sessions#book", as: "session_booking"

  get "/tax" => "categories#tax", as: "tax"
  get "/investments" => "categories#investments", as: "investments"
  get "/personal_finance" => "categories#personal_finance", as: "personal_finance"
  get "/insurance" => "categories#insurance", as: "insurance"
  get "/trading" => "categories#trading", as: "trading"

end

app/models/consultant.rb
class Consultant < ApplicationRecord
	belongs_to :user
	has_many :category_consultants
	has_many :categories, through: :category_consultants, foreign_key: 'category_id'
	has_many :users
	has_many :consultant_sessions

	validates :qualifications, :languages, :location, presence: true

end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
	before_action :require_login

	def new
		unless current_user.consultants.empty?
			redirect_to consultant_path(current_user.consultants.last)
		end
		@consultant = Consultant.new
		@category = @consultant.categories.new
	end

	def create
		@user_id = :user_id
		@consultant = current_user.consultants.new(consultant_params)
		if @consultant.save
			@consultant.categories.create!(category_params)
			redirect_to edit_consultant_path(@consultant)
		else
			render :action => "new"
		end
	end

	def show
		@consultant = Consultant.find(params[:id])
	end

	def index
		@consultants = Consultant.all
	end

	def edit
		@consultant = Consultant.find(params[:id])
		@category = @consultant.categories.new
	end

	def update
		@consultant = Consultant.find(params[:id])
		#	@consultant = Consultant.find_by(user_id: params[:user_id])?
		if  @consultant.update_attributes(consultant_params)
			@consultant.user.name = params[:consultant][:user][:name]
			@consultant.description = params[:consultant][:description]
			@consultant.save!
			@consultant.user.save!
			redirect_to :action => 'show', :id => @consultant
		else
			render :action => 'edit'
	 	end
	end

   def delete
      Consultant.find(params[:id]).destroy
      redirect_to :action => 'list'
   end

	private
		def consultant_params
	   params.require(:consultant).permit(:qualifications, :languages, :location, :user_id)
	   # params.require(:user).permit(:name, :email)
		end

		def category_params
			params.require(:category).permit(:category_name)
		end

		# def updated_consultant_params
		# 	params.require(:consultant).permit(:name)
		# end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/_edit_form.html.erb
<div class="row">
<div class="border">
  <%= form_for @consultant do |form| %>
		
		<%= form.fields_for @consultant.user do |form_fields| %>
			Name: <%= form_fields.text_field :name %>
		<% end %>

	  <div class="col-md-8">
	    <h2 class="a">Edit Profile</h2>

			<div class="text-field">
			  <label for="qualifications">Qualifications:</label>
			  <%= form.text_field :qualifications, placeholder: "Enter Your Qualifications" %>
			</div><br>

			<div class="text-field">
			<label for="languages">Languages:</label>
			  <%= form.text_field :languages, placeholder: 'Enter Your Languages' %>
			</div><br>


			<div class="text-field">
			<label for="location">Location:</label>
			  <%= form.text_field :location, placeholder: 'Enter Your Location' %>
			</div><br>

			<div class="text-field">
			<label for="description">Description:</label>
			  <%= form.text_field :description, placeholder: 'Enter Your Description' %>
			</div><br>

			

		  <%= form.label "Upload a profile picture" %>
			<div class="file-field ">
		 		<center> 
		  		<%= form.file_field :profile_picture %>
				</center>
			</div><br>

			<div class="submit-field">
		      <%= form.submit %>
		  </div>
		</div>

	<% end %>
	</div>
</div>

app/views/consultants/_form.html.erb
<%= form_for @consultant do |form| %>
  <div class="text-field">
    <%= form.text_field :qualifications, placeholder: 'Enter Your Qualifications' %>
  </div><br>

  <div class="text-field">
    <%= form.text_field :languages, placeholder: 'Enter Your Languages' %>
  </div><br>

  <div class="text-field">
    <%= form.text_field :location, placeholder: 'Enter Your Location' %>
  </div><br>

  
  <%= form_for @category do |form| %>
    <div class="text-field">
      <%= form.label "Field of expertise"%>
      <%= form.select(:category_name, ['Loans', 'Tax', 'Investments', 'Personal Finance', 'Insurance', 'Trading']) %>
    </div>

  <div class="submit-field">
    <%= form.submit %>
  </div>
  <% end %>
<% end %>

app/views/consultants/edit.html.erb
<div class="container-fluid text-center bodyWrapper">
<div class="form-edit">
  <%= render 'edit_form' %>
</div>
</div>

app/views/consultants/index.html.erb
<% @consultants.each do |c| %>
  <h3><%= c.user.name %></h3>
  <p>Location: <%= c.location %></p>
  <p>Languages: <%= c.languages %></p>
  <p>Qualifications: <%= c.qualifications %></p>
  <a href="/consultants/<%= c.id %>">Profile</a>
<% end %>

app/views/consultants/new.html.erb
<div class="container-fluid text-center bodyWrapper">
  <br />
  <br />
  <div class="form-consultant">
    <h2>Apply to be a consultant</h2>
    <%= render partial: '/consultants/form'%>

  </div>
</div>

app/views/consultants/show.html.erb
<div class="bodyWrapper">
  <div class="container-fluid">
    <div class="profileWrapper">
      <div class="alignText">
        <p class="mediumText">
          <strong><%= @consultant.user.name %></strong>
        </p>
        <% if current_user.id == @consultant.user.id %>
          <p>
            <%= link_to 'Edit profile', edit_consultant_path(@consultant) %>
          </p>
        <% end %>
      </div>
      <br />
      <br />
      <div class="row">
        <div class="col-sm-9">
          <p class="smallText">
           <strong>Qualifications:</strong>
           <%= @consultant.qualifications %>
          </p>

          <p class="smallText">
           <strong>Languages:</strong>
           <%= @consultant.languages %>
          </p>

          <p class="smallText">
           <strong>Location</strong>
           <%= @consultant.location %>
          </p>

          <p class="smallText">
           <strong>Description</strong>
           <%= @consultant.description %>
          </p>
        </div>

        <div class="col-sm-3">
          <%= image_tag(@consultant.user.avatar.square.url, class: 'profileThumb') if @consultant.user.avatar.square.url %>
        </div>
      </div>
    </div>

    <br />

    <%= link_to user_path(@consultant.user) do %>
      <div class="buttonWrapper alignText">
        <br />
        <p>
          View Sessions
        </p>
      </div>
    <% end %>

    <br />

    <%= form_tag new_payment_path, method: :get do %>

    <% if current_user.id == @consultant.user.id %>
      <%= link_to new_consultant_session_path do %>
        <div class="buttonWrapper alignText">
          <br />
          <p>
            Create a consultant session
          </p>

        </div>
      <% end %>
    <% end %>

    <br />
    <br />

      <div class="longButtonWrapper alignText">
        <br />
        <p>
          AVAILABLE SESSIONS
        </p>
      </div>

    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>#</th>
          <th>Date</th>
          <th>Day</th>
          <th>Time</th>
          <th>Cost</th>
          <th>Select</th>
        </tr>
      </thead>
      <tbody>

      <% count = 0 %>
        <% @consultant.user.consultant_sessions.where(session_active_inactive: true).each do |s| %>
          <tr>
            <th scope="row"><%= count += 1 %></th>
            <td><%= s.start_time.to_date %></td>
            <td><%= s.start_time.to_date.wday %></td>
            <td><%= s.start_time.time.to_formatted_s(:time) %></td>
            <td><%= s.rate %></td>
            <td><%= check_box_tag "consult_sessions[#{s.id}]" %></td>
          </tr>
        <% end %>
          <tr>
            <td colspan="6"><button type="submit" class="btn btn-primary pull-right">Submit</button></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
</div>