config/routes.rb
Rails.application.routes.draw do

  # Root page
  root to: "home#show"
  resource :home, only: [:show]

  # User sign up, sign in, and log in/log out
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :update, :show, :index] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  # routes for chat_rooms
  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'

  # routes for consultants
  resources :consultants

  # routes for consultant sessions
  resources :consultant_sessions do
    member do
      get '/video' => 'consultant_sessions#video', as: 'video'
    end
  end

  #routes for categories
  resources :categories, only: [:show, :index]
  get "/loans" => "categories#loans", as: "loans"

  resources :payments, only: [:new, :create]

  post '/consultants/:consultant_id/book_session', to: "consultant_sessions#book", as: "session_booking"

  get "/tax" => "categories#tax", as: "tax"
  get "/investments" => "categories#investments", as: "investments"
  get "/personal_finance" => "categories#personal_finance", as: "personal_finance"
  get "/insurance" => "categories#insurance", as: "insurance"
  get "/trading" => "categories#trading", as: "trading"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories.rb
class Category < ApplicationRecord
	has_many :consultants

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :category_consultants
	has_many :consultants, through: :category_consultants, foreign_key: 'consultant_id'

end

app/models/category_consultant.rb
class CategoryConsultant < ApplicationRecord
  belongs_to :category
  belongs_to :consultant
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  belongs_to :consultant_session
end

app/models/consultant.rb
class Consultant < ApplicationRecord
	belongs_to :user
	has_many :category_consultants
	has_many :categories, through: :category_consultants, foreign_key: 'category_id'
	has_many :users
	has_many :consultant_sessions

	validates :qualifications, :languages, :location, presence: true

end

app/models/consultant_session.rb
class ConsultantSession < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :consultant, class_name: 'User'
  has_many :chat_rooms
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/payment.rb
class Payment < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :consultants
  has_many :consultant_sessions, foreign_key: "consultant_id"
  has_many :consulting_sessions, class_name: "ConsultantSession", foreign_key: "user_id"
  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.email = auth[:info][:email]
      user.password = ('0'..'z').to_a.shuffle.first(8).join
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def loans
		@category = Category.includes(consultants: :user).where("category_name like ?", "Loans")
	end

	def tax
		@category = Category.includes(consultants: :user).where("category_name like ?", "Tax")
	end

	def investments
		@category = Category.includes(consultants: :user).where("category_name like ?", "Investments")
	end

	def personal_finance
		@category = Category.includes(consultants: :user).where("category_name like ?", "Personal Finance")
	end

	def insurance
		@category = Category.includes(consultants: :user).where("category_name like ?", "Insurance")
	end

	def trading
		@category = Category.includes(consultants: :user).where("category_name like ?", "Trading")
	end

	def index
		@categories = Category.all
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @categories = Category.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @client_token = Braintree::ClientToken.generate
    @total_cost = 0
    @consult_sessions = params[:consult_sessions].keys
    params[:consult_sessions].keys.each do |id|
      @consultant_session = ConsultantSession.find(id)
      @total_cost += @consultant_session.rate
    end
  end

  def create
    consult_sessions = params[:payment][:consult_sessions].split(" ")
    nonce = params[:payment_method_nonce]
    render action: :new and return unless nonce
    result = Braintree::Transaction.sale(
      amount: params[:payment][:total_cost],
      payment_method_nonce: params[:payment_method_nonce]
    )
    if result.success?
      consult_sessions.each do |id|
        @consultant_session = ConsultantSession.find(id)
        @consultant_session.update(user_id: current_user.id, session_active_inactive: false)
      end 
      flash[:success] = 'Payment has been made successfully'
      redirect_to root_path
    else
      flash[:error] = 'There was a problem with payment. Please try again.'
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.from_omniauth(env["omniauth.auth"])
    if sign_in(user)
      redirect_to edit_user_path(user)
    else
      redirect_to sign_in_path
    end


  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

before_action :set_user, only: [:show]

	def create
	    @user = user_from_params
	    if @user.save
	      ConfirmationMailer.confirmation_email(@user).deliver
	      sign_in @user
	      redirect_back_or url_after_create
	    else
	      flash[:message] = 'Invalid email/password combination'
	      render template: "users/new"
	    end
	  end

  def show

  end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
        if @user.update(filtered_user_params)
          redirect_to root_path
        else
          flash[:alert] = 'Error'
          render :edit
        end
    end

	private

	def user_from_params
	    email = user_params.delete(:email)
	    password = user_params.delete(:password)
	    birthday = user_params.delete(:birthday)
	    profile_picture = user_params.delete(:avatar)

	    Clearance.configuration.user_model.new(user_params).tap do |user|
	      user.email = email
	      user.password = password
	      user.birthday = birthday
	      user.avatar = profile_picture
	    end
	end

	def edit_user_params
		params.require(:user).permit(:email, :password, :birthday, :avatar)
	end

	def filtered_user_params
		if edit_user_params[:password].empty?
			edit_user_params.except(:password)
		else
			edit_user_params
		end
	end

   def set_user
     @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find(session[:user_id])
  end
end

app/views/categories/_index.html.erb
<div class="container-fluid text-center">
  <p class="mediumText"><strong>I want advice for...</strong></p>
  <br />
  <br />
  <div class="row">
    <div class="col-sm-4">
      <%= link_to loans_path do %>
        <div class="categoryBox loans">
          <div class="mediumText">
            <p><strong>LOANS</strong></p>
          </div>
        </div>
        <% end %>
    </div>

    <div class="col-sm-4">
      <%= link_to tax_path do %>
        <div class="categoryBox tax">
          <div class="mediumText">
            <p><strong>TAX</strong></p>
          </div>
        </div>
        <% end %>
    </div>

    <div class="col-sm-4">
      <%= link_to investments_path do %>
        <div class="categoryBox investments">
          <div class="mediumText">
            <p><strong>INVESTMENTS</strong></p>
          </div>
        </div>
        <% end %>
    </div>
  </div>
<br />
    <div class="row">
      <div class="col-sm-4">
        <%= link_to personal_finance_path do %>
          <div class="categoryBox personalFinance">
            <div class="mediumText">
              <p><strong>PERSONAL</strong></p>
              <p><strong>FINANCE</strong></p>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-sm-4">
        <%= link_to insurance_path do %>
          <div class="categoryBox insurance">
            <div class="mediumText">
              <p><strong>INSURANCE</strong></p>
            </div>
          </div>
          <% end %>
      </div>

      <div class="col-sm-4">
        <%= link_to trading_path do %>
          <div class="categoryBox trading">
            <div class="mediumText">
              <p><strong>TRADING</strong></p>
            </div>
          </div>
          <% end %>
        </div>
    </div>

app/views/categories/_sidebar.html.erb
<div class="col-sm-2">
  <div id="sidebar-wrapper">
    <div class="sidebarBrand alignText">
      <p class="smallText sidebarText">
        <strong>CATEGORIES</strong>
      </p>
    </div>
    <ul class="sidebar-nav sidebarNav">
      <li>
        <%= link_to "Loans", loans_path %>
      </li>
      <li>
        <%= link_to "Tax", tax_path %>
      </li>
      <li>
        <%= link_to "Investments", investments_path %>
      </li>
      <li>
        <%= link_to "Personal Finance", personal_finance_path %>
      </li>
      <li>
        <%= link_to "Insurance", insurance_path %>
      </li>
      <li>
        <%= link_to "Trading", trading_path %>
      </li>
    </ul>
  </div>
</div>

app/views/categories/index.html.erb
<h2>Categories available</h2>
<% @categories.each do |c| %>
	<a href="/categories/<%=c.id%>"><%= c.category_name %></a><br>
<% end %> 

app/views/categories/insurance.html.erb
<div class = "bodyWrapper">
  <div class="container-fluid">
    <div class="row">
      <%= render "/categories/sidebar" %>
      <div class="col-sm-10">
        <h2><%= @category.first.category_name %></h2>
        <% @category.each do |category| %>
        <% category.consultants.all.each do |c|  %>
        <div class="container-fluid consultantWrapper">
          <p>
            <%= link_to consultant_path(Consultant.find(c.id)) do %>
            <%= c.user.name %>
            <% end %>
            <%= c.qualifications %>
            <%= c.languages %>
          </p>
          <p>
            <%= c.description %>
          </p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/investments.html.erb
<div class = "bodyWrapper">
  <div class="container-fluid">
    <div class="row">
      <%= render "/categories/sidebar" %>
      <div class="col-sm-10">
        <h2><%= @category.first.category_name %></h2>
        <% @category.each do |category| %>
        <% category.consultants.all.each do |c|  %>
        <div class="container-fluid consultantWrapper">
          <p>
            <%= link_to consultant_path(Consultant.find(c.id)) do %>
            <%= c.user.name %>
            <% end %>
            <%= c.qualifications %>
            <%= c.languages %>
          </p>
          <p>
            <%= c.description %>
          </p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/loans.html.erb
<div class = "bodyWrapper">
  <div class="container-fluid">
    <div class="row">
      <%= render "/categories/sidebar" %>
        <div class="col-sm-10">

          <div class="jumbotron categoryHeader">
            <p><strong>MEET OUR LOAN EXPERTS!</strong></p>
          </div>

          <% @category.each do |category| %>
            <% category.consultants.all.each do |c|  %>
              <%= link_to consultant_path(Consultant.find(c.id)) do %>
                <div class="container-fluid consultantWrapper">
                  <div class="col-sm-3">
                    <br />
                    <%= image_tag(c.user.avatar.square.url, class: 'profileThumb') if c.user.avatar.square.url %>
                  </div>
                  <div class="col-sm-7">
                    <br />
                    <p class="mediumText">
                      <strong><%= c.user.name %></strong>
                    </p>
                    <br />
                    <p class="extrasmallText">
                      <strong>QUALIFICATIONS: </strong><%= c.qualifications %>
                    </p>
                    <p class="extrasmallText">
                      <strong>LANGUAGES SPOKEN: </strong><%= c.languages %>
                    </p>
                    <p class="extrasmallText">
                      <strong>WORKS AT: </strong>NEXT Financial Services
                    </p>
                    <p>
                      <%= c.description %>
                    </p>
                  </div>
                </div>
              <% end %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/personal_finance.html.erb
<div class = "bodyWrapper">
  <div class="container-fluid">
    <div class="row">
      <%= render "/categories/sidebar" %>
      <div class="col-sm-10">
        <h2><%= @category.first.category_name %></h2>
        <% @category.each do |category| %>
        <% category.consultants.all.each do |c|  %>
        <div class="container-fluid consultantWrapper">
          <p>
            <%= link_to consultant_path(Consultant.find(c.id)) do %>
            <%= c.user.name %>
            <% end %>
            <%= c.qualifications %>
            <%= c.languages %>
          </p>
          <p>
            <%= c.description %>
          </p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/tax.html.erb
<div class = "bodyWrapper">
  <div class="container-fluid">
    <div class="row">
      <%= render "/categories/sidebar" %>
      <div class="col-sm-10">
        <h2><%= @category.first.category_name %></h2>
        <% @category.each do |category| %>
        <% category.consultants.all.each do |c|  %>
        <div class="container-fluid consultantWrapper">
          <p>
            <%= link_to consultant_path(Consultant.find(c.id)) do %>
            <%= c.user.name %>
            <% end %>
            <%= c.qualifications %>
            <%= c.languages %>
          </p>
          <p>
            <%= c.description %>
          </p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/trading.html.erb
<div class = "bodyWrapper">
  <div class="container-fluid">
    <div class="row">
      <%= render "/categories/sidebar" %>
      <div class="col-sm-10">
        <h2><%= @category.first.category_name %></h2>
        <% @category.each do |category| %>
        <% category.consultants.all.each do |c|  %>
        <div class="container-fluid consultantWrapper">
          <p>
            <%= link_to consultant_path(Consultant.find(c.id)) do %>
            <%= c.user.name %>
            <% end %>
            <%= c.qualifications %>
            <%= c.languages %>
          </p>
          <p>
            <%= c.description %>
          </p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="bodyWrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-6">
				<a class="buttonContainer" href="/consultants/new">
					<div class="wantToAdvice"></div>
						<div class="container-fluid alignText">
							<p class="mediumText pushUp">
								<strong>I AM</strong>
							</p>
							<br />
							<p class="largeText pushUp">
								<strong>A FINANCIAL ADVISOR</strong>
							</p>
						</div>
					</a>
				</div>

			<div class="col-sm-6">
				<a class="buttonContainer" href="#categories">
					<div class="wantAdvice"></div>
					<div class="container-fluid alignText">
						<p class="mediumText pushUp">
							<strong>I AM</strong>
						</p>
						<br />
						<p class="largeText pushUp">
							<strong>LOOKING FOR FINANCIAL</strong>
						</p>
						<br />
						<p class="largeText pushUp">
							<strong>ADVICE</strong>
						</p>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>



<div class="container-fluid">
	<div class="landingBanner alignText">
		<p class="mediumText"><strong>FREEDOM THROUGH FINANCIAL LITERACY</strong></p>
		<br />
		<br />
		<p class="smallText">
			Always wanted to get some financial advice but didn't know where to get started? Overwhelmed by the sheer amount of information on the web? Want a specific answer to a personal financial question?
		</p>
		<br />
		<p class="smallText">
			Making Cents has the answers for you! Search and compare financial advisors to get the best fit for you. Get quick individualized advice for extremely affordable rates. Seek second or third (or more!) opinions on various financial matters. It's financial advice without any pressure, from the comfort of your home.
		</p>
		<br />
		<p class="smallText">
			Making Cents. Your one-stop financial advice solution.
		</p>
	</div>
</div>

<div id="categories">
	<%= render "categories/index" %>
</div>


<br />
<br />
<div class="container-fluid">
	<div class="pageFooter alignText">
		<br />
		<p class="mediumText footerText">
			<strong>Contact us!</strong>
		</p>

		<p class="extrasmallText footerText">
			Making Cents was developed over 5 days as a final project for a web development bootcamp. Please reach out to us if you would like more information.
		</p>
		<br />

		<div class="contactRow">
			<a href="https://www.facebook.com/danielgohkengyu" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
			<a href="https://github.com/gohdaniel15" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
			<a href="https://my.linkedin.com/in/danielgohky" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
		</div>

	</div>
</div>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <!-- user image goes here -->
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.email %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<div class="form-horizontal" role="form">
			<div class="form-group">
    			<label class="control-label col-sm-2" for="email">Email:</label>
    			<div class="signup-form-field">
    				<%= form.email_field :email, class: 'form-control', id: 'email', placeholder: 'Enter a valid email address' %>
    			</div>
			</div>

			<div class="form-group">
			    <label class="control-label col-sm-2" for="pwd">Password:</label>
			    <div class="signup-form-field">
			    	<%= form.password_field :password, class: 'form-control', id: 'pwd', placeholder: 'Enter a valid password' %>
			    </div>
			</div>

			<div class="form-group">
			    <label class="control-label col-sm-2" for="dob">Birthday:</label>
			    <div class="signup-form-field"> 
			    	<%= form.text_field :birthday, class: 'form-control', id: 'dob', placeholder: 'DD/MM/YYYY' %>
			    </div>
			</div>

			<div class="form-group">
			<label class="control-label col-sm-2" for="pp">Profile Picture:</label>
			<div class="signup-form-field"> 
			  <%= form.file_field :avatar %> <br>
			</div>


			<div class="action">				
      			<%= form.submit "Create" , class: "btn-sign-up"%>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid bodyWrapper">
  <%= form_for @user do |form| %>

  <div class="text-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="password-field">
    <%= form.label :birthday%>
    <%= form.text_field :birthday %>
  </div>

  <div class="file-field">
    <%= form.label "Upload a profile picture" %>
    <%= form.file_field :avatar %>
  </div>

    <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<table>
    <tr>
        <th>No.</th>
        <th>email</th>

    <% User.all.each do |l| %>
    <% n = 1 %>
    <tr>
        <th><%= n %></th>
        <% n += 1 %>
        <td><%= l.email %></td>
        </td>
    </tr>
    <%end%>
</table>


app/views/users/new.html.erb
<div class = "clearance">
  <div class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
   <%= render partial: '/users/form', object: form %> 
  <% end %>
  </div>
  <div class="row">
    <%= link_to "Sign up with Google", "/auth/google_oauth2", id: "sign_in", class: "btn-google" %>
    <%= link_to "Sign up with Facebook", "/auth/facebook", id: "sign_in", class: "btn-fb" %>
    <div class="other-links">
      <p>Already have an account with us?
        <%= link_to t(".sign_in"), sign_in_path %>
      </p>
    </div>
  </div>
  </div>        
</div>    

app/views/users/show.html.erb
<div class="bodyWrapper">
  <div class="container-fluid">
    <div class="profileWrapper">
      <div class="alignText">
        <p class="mediumText">
          <strong><%= @user.name %></strong>
        </p>
        <% if current_user.id == @user.id %>
          <p>
            <%= link_to 'Edit profile', edit_user_path(@user) %>
          </p>
        <% end %>
      </div>
      <br />
      <br />
      <div class="row">
        <div class="col-sm-9">
          <p class="smallText">
           <strong>Email:</strong>
           <%= @user.email %>
          </p>

          <!-- Add user languages and locations. -->

        </div>

        <div class="col-sm-3">
          <%= image_tag(@user.avatar.square.url, class: 'profileThumb') if @user.avatar.square.url %>
        </div>
      </div>
    </div>

    <br />

    <div class="longButtonWrapper alignText">
      <br />
      <p>
        RESERVED SESSIONS
      </p>
    </div>

    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>#</th>
          <th>Date</th>
          <th>Day</th>
          <th>Time</th>
          <th>Cost</th>
          <th>Chat Link</th>
        </tr>
      </thead>
      <tbody>
      <% count = 0 %>
        <% @user.consulting_sessions.each do |s| %>
          <tr>
            <th scope="row"><%= count += 1 %></th>
            <td><%= s.start_time.to_date %></td>
            <td><%= s.start_time.to_date.wday %></td>
            <td><%= s.start_time.time.to_formatted_s(:time) %></td>
            <td><%= s.rate %></td>
            <td>
              <p>
                <%= link_to '/chat_rooms/1' do %><button class="btn btn-primary">Enter Chat</button><% end %>
              </p>
              <% if !s.video_sessions_id.nil? && s.user_id == current_user.id %>
                <p><%= link_to 'Start Video Session', video_consultant_session_path(s.id), data: { turbolinks: 'false' } %></p>
              <% end %>
          </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>